local class = require("engine.class")
local Birther = require("engine.Birther")
local Talents = require("engine.interface.ActorTalents")
local ActorTemporaryEffects = require("engine.interface.ActorTemporaryEffects")

class:bindHook("ToME:load", function(self, data)
	Talents:loadDefinition("/data-forsaken/talents/cursed/forsaken.lua")
	Birther:loadDefinition("/data-forsaken/birth/classes/afflicted.lua")
	ActorTemporaryEffects:loadDefinition("/data-forsaken/timed_effects/mental.lua")
end)
